ConductionNL/openregister

lib/Service/ObjectService.php

- Not being able to upload files from OpenCatalogi frontend
- Share link instead of download link

Fix two small bugs

---

lib/Service/FileService.php
lib/Service/ObjectService.php

Development to main

---

docs/events.md
lib/Controller/ObjectsController.php
lib/Db/ObjectEntityMapper.php
lib/Db/RegisterMapper.php
lib/Db/SchemaMapper.php
lib/Event/ObjectCreatedEvent.php
lib/Event/ObjectDeletedEvent.php
lib/Event/ObjectUpdatedEvent.php
lib/Event/RegisterCreatedEvent.php
lib/Event/RegisterDeletedEvent.php
lib/Event/RegisterUpdatedEvent.php
lib/Event/SchemaCreatedEvent.php
lib/Event/SchemaDeletedEvent.php
lib/Event/SchemaUpdatedEvent.php

Events wil allow us to build easy integrations from open connector

Add events to Open Register

---

lib/Service/FileService.php

https://conduction.atlassian.net/browse/IBOC-148

IBOC-148 > Fix for setting folder property correctly

---

lib/Service/FileService.php
lib/Service/ObjectService.php

- Set proper user on file functions
- Provide a quick add file route

Refactor on file service

---

lib/Service/FileService.php

Set correct user for file ownership

---

lib/Service/ObjectService.php
src/modals/schema/EditSchemaProperty.vue

Dev to main

---

lib/Db/Schema.php
lib/Service/ObjectService.php

Also fixes ZAAKREG-49 about validating object uris

Set objects with id or uri

---

lib/Service/FileService.php

Co-authored-by: Robert Zondervan <robert@conduction.nl>

Fixed publication file total being the same as limit

---

lib/Db/Schema.php

Also unset $ref before validating

Set property oneOf uri or object

---

.github/workflows/beta-release.yaml

So we can create dev build from development

Added beta release flow from code-refactor to development

---

lib/Controller/ObjectsController.php
lib/Db/AuditTrailMapper.php
lib/Service/ObjectHandlers/RenderObject.php

Fix extend on single object

---

src/modals/object/ViewObject.vue

Please use objectStore, or any other store without "this.".

Data view is now visible

---

appinfo/routes.php
lib/Controller/ObjectsController.php
lib/Db/Schema.php
lib/Service/ObjectService.php

There where several error preventing proper handling of validation
- All properties where set as required before validation
- Unimported classes where used
- Unsupported properties on classes where callled
This fix does not solve ui issues , backend only

Fix errors in validation

---

lib/Db/AuditTrailMapper.php
lib/Db/ObjectEntityMapper.php
lib/Service/ObjectHandlers/DeleteObject.php

Also, fit dispatching object deleted events to current api standard

Fix audit logging on deletes

---

src/sidebars/register/RegisterSideBar.vue

1 line change, please lint don't kill me

title parameter changed to name parameter

---

lib/Service/ObjectHandlers/DeleteObject.php
lib/Service/ObjectHandlers/SaveObject.php

- Fix for saving object which schema has no slug
- Fix for deleting files of object when deleting that object

Fix for deleting files when deleting a object

---

appinfo/routes.php
lib/Controller/ObjectsController.php
lib/Service/ObjectService.php

This hotfix introduces support for patching objects

Hotfix patching

---

lib/Db/SchemaMapper.php
lib/Service/ObjectHandlers/ValidateObject.php
lib/Service/ObjectService.php
src/modals/schema/EditSchema.vue
website/docs/Features/enhanced-validation-errors.md

Removed properties could still be required cousing a catch 22. This fix contains both front and backend fixes for that

Hotfix for required properties

---

lib/Db/Schema.php
lib/Service/ObjectHandlers/RenderObject.php
lib/Service/ObjectHandlers/ValidateObject.php
lib/Service/ObjectService.php

Also, fix a number of small bugs regarding errors and validation

Fix inversedBy in the ZGW case

---

.gitignore
lib/Service/FileService.php

By checking the md5 checksum of the existing file and the content of the incoming data.

Prevent writing unchanged files

---

BULK_SAVE_PERFORMANCE_OPTIMIZATION.md
SMART_DEDUPLICATION_IMPACT_AND_CHANGES.md
SMART_DEDUPLICATION_SYSTEM.md
composer.json
composer.lock
lib/AppInfo/Application.php
lib/Controller/HeartbeatController.php
lib/Controller/ObjectsController.php
lib/Db/Schema.php
lib/Migration/Version1Date20250902140000.php
lib/Migration/Version1Date20250902150000.php
lib/Service/ObjectHandlers/SaveObjects.php
lib/Service/ObjectService.php
lib/Settings/softwarecatalogus_register.json

ets make sure that _search never touches the json but alwasy name, description and summery to prevent unnesessery json searches
todo: Lets test that by also geting queries with _search under 750ms
todo: And did you finisch al your improvements?
todo:And did you run the migrations you mad?
todo: Did we add setting the facets on a schema creation and changes to the @SchemaMapper.php 
Ensure _search only touches name, description, and summary fields, never the JSON object field to prevent expensive JSON searches
Check if all database migrations were run successfully
Add facet setting functionality to SchemaMapper.php for schema creation and updates
Test that queries with _search parameter are under 750ms
Verify all performance improvements are completed and working
✅ All TODOs Completed …

Hotfix: Speedimprovements

---

src/views/settings/SolrDashboard.vue

The SOLR dashboard was stuck in an infinite loading state when SOLR was unavailable, creating a catch-22 situation where users couldn't access the SOLR configuration to fix the connection issue.
- Add proper error handling in loadSolrStats() method
- Show error state instead of infinite loading spinner  
- Add retry button for reconnection attempts
- Display helpful error messages and troubleshooting tips
- Clear error state when connection is successfully restored
- Enhanced error handling in `loadSolrStats()` method
- Added `solrError` and `solrErrorMessage` data properties
- Added error UI state with clear messaging and retry functionality
- Updated template logic to handle error states properly
- Dashboard now shows error state instead of infinite loading when SOLR is unavailable
- …

hotfix: Fix SOLR dashboard infinite loading when SOLR is unavailable

---

lib/Service/GuzzleSolrService.php
lib/Service/SettingsService.php
lib/Service/SolrSchemaService.php
lib/Setup/SolrSetup.php

This PR centralizes SOLR operations through GuzzleSolrService and significantly improves error handling and diagnostics for SOLR setup and testing operations.
- **SettingsService**: Refactored  to delegate to 
- **Deprecated Methods**: Marked old direct test methods in SettingsService as deprecated
- **Consistent Configuration**: All SOLR operations now use the same configuration and URL construction logic
- **SolrSetup**: Added comprehensive error messages with troubleshooting steps
- **HTTP Error Details**: Include detailed HTTP request/response information
- **JSON Validation**: Proper handling of invalid JSON responses from SOLR
- **Step-by-step Progress**: Detailed logging during setup process
- **Actionable Feedback**: Specific troubleshooting tips for common issues
- **Kubernetes …

feat(solr): centralize SOLR operations and enhance error handling

---

PR adds comprehensive unit tests covering **ALL 25+ SettingsController endpoints** and implements critical bug prevention measures.
`, `clearCache`, `warmupNamesCache`
`, `updateMultitenancySettings`
`, `updateRbacSettings`
`, `updateRetentionSettings`
circular references and encoding issues
docs/TESTING_IMPROVEMENTS.md
e Analysis**: Detailed explanation of the json_decode Stream bug
hingOptions`, `rebase`
lib/Controller/SettingsController.php
lib/Service/SettingsService.php
tSolrConnection`, `setupSolr`, `testSolrSetup`
tests/Integration/SolrApiIntegrationTest.php
tests/Unit/Controller/SettingsControllerTest.php

- ✅ **Fixed json_decode Stream TypeError**: Resolved  by casting response bodies to string
- ✅ **Fixed Port 0 URL Issues**: Prevented malformed URLs with  in SOLR/Zookeeper connections
- ✅ **Fixed Kubernetes Service Handling**: Proper URL construction for  service names without appending ports
- ✅ **Fixed Undefined Variable Error**: Resolved  undefined variable in 
- ✅ **Detailed SOLR Setup Errors**: Replaced generic "check logs" messages with comprehensive error details including:
- Primary error descriptions
- Possible causes (permissions, SolrCloud mode, connectivity)
- Configuration used (host, port, scheme, path, generated URLs)
- Step-by-step troubleshooting instructions
- Last system error capture
- ✅ **URL Validation**: Error responses now show the exact URLs being attempted
- ✅ …

feat(solr): comprehensive SOLR testing enhancements and error reporting improvements

---

lib/Controller/SettingsController.php
lib/Service/GuzzleSolrService.php
lib/Service/SettingsService.php
lib/Service/SolrSchemaService.php
lib/Setup/SolrSetup.php
tests/Unit/Controller/SettingsControllerTest.php
tests/Unit/Service/SettingsServiceTest.php

This PR implements a comprehensive refactoring of SOLR services with extensive testing improvements and architectural cleanup.
- ✅ Updated `SettingsController` to use `GuzzleSolrService` directly for:
- `testSolrConnection()`
- `warmupSolrIndex()`
- `getSolrDashboardStats()`
- `manageSolr()`
- ✅ Added `testConnectionForDashboard()` method to `GuzzleSolrService`
- ✅ Deprecated `testSolrConnectionForDashboard()` in `SettingsService` with delegation
- ✅ Added `getEndpointUrl()` method to `GuzzleSolrService`
- ✅ Removed duplicate `buildSolrEndpointUrl()` from `SettingsService`
- ✅ Consolidated all URL building into existing `buildSolrBaseUrl()` method
- ✅ **SettingsServiceTest.php**: 25+ test methods covering all public methods
- ✅ **SolrApiIntegrationTest.php**: Integration tests for SOLR …

refactor(solr): Complete 3-phase SOLR service refactoring and testing enhancements

---

lib/Controller/SettingsController.php
lib/Setup/SolrSetup.php

This PR significantly improves SOLR error diagnosis by returning **actual HTTP error details** instead of generic error messages, and centralizes authentication in GuzzleSolrService for consistent security across all SOLR operations.
- **✅ Real HTTP Error Details**: API now returns actual SOLR response bodies, status codes, and error messages
- **✅ Error Categorization**: Automatic classification (authentication, network, SOLR API, invalid JSON)
- **✅ Comprehensive Debugging**: Guzzle request/response details, exception types, and troubleshooting tips
- **✅ Detailed API Responses**: Replace generic "HTTP request failed" with specific diagnostic information
- **✅ Unified Authentication**: All SOLR HTTP calls now use authenticated client from GuzzleSolrService
- **✅ Dependency Injection**: …

feat(solr): Enhanced SOLR error reporting and authentication centralization

---

lib/Service/GuzzleSolrService.php

- Removed Git merge conflict markers from getTenantId() method docblock
- Resolved conflicting implementations in isAvailable() method
- Chose improved version with better error handling and configuration validation
- All PHP syntax errors resolved

fix: resolve merge conflicts in GuzzleSolrService.php

---

lib/Controller/ObjectsController.php
lib/Service/GuzzleSolrService.php
lib/Service/ObjectService.php
src/sidebars/search/SearchSideBar.vue
src/store/modules/object.js
src/views/search/SearchIndex.vue

This hotfix improves SOLR facet handling specifically for @self metadata fields:
- Enhanced GuzzleSolrService to properly handle @self metadata facets
- Added support for date histogram facets with proper Solr configuration
- Improved facet field mapping for self metadata fields  
- Updated search sidebar and object store for better facet integration
- Modified facet processing logic to differentiate between @self metadata and regular facets
- Added proper field name mapping (self_ prefix) for metadata fields
- Implemented date histogram support for temporal faceting
- Enhanced error handling and logging for facet operations
- Verified facet functionality with various metadata field types
- Tested date histogram facets with temporal data
- Confirmed backward compatibility with existing …

Hotfix: Improve SOLR facet handling for @self metadata

---

lib/Service/GuzzleSolrService.php
lib/Service/ObjectService.php
openregister/.gitignore
website/docs/solr-search-engine.md

This hotfix completes the SOLR search integration improvements, resolving pagination issues and ensuring proper error handling.
- **Fixed pagination**: API now correctly returns requested number of results with accurate totals
- **Proper source attribution**: Responses correctly show `"source": "index"` when using SOLR
- **Weighted search fields**: Optimized to use only essential fields:
- `self_name` (15x weight) - highest priority
- `self_summary` (10x weight) - medium-high priority  
- `self_description` (5x weight) - medium priority
- `_text_` (1x weight) - catch-all full-text
- **Simplified source selection**: Clean logic in ObjectService.php for SOLR vs database routing
- **Transparent error handling**: Clear error messages when SOLR fails instead of silent fallback
- **Enhanced …

Hotfix: Complete SOLR search integration improvements

---

appinfo/routes.php
lib/Controller/SettingsController.php
lib/Service/GuzzleSolrService.php
lib/Service/SolrSchemaService.php
src/store/settings.js
src/views/settings/sections/SolrConfiguration.vue

This PR fixes critical issues with SOLR field mismatch detection and fixing functionality.
- **🐛 Fixed critical parameter swap bug** in compareFields() method calls that was causing incorrect field comparisons
- **🔧 Added dedicated fixMismatchedFields() method** separate from createMissingFields() for better separation of concerns  
- **🎯 Implemented named parameters** to prevent future parameter order bugs
- **⚡ Added spinner UI state** for fix mismatched fields button with separate fixingFields state
- **🎨 Enhanced SOLR field configuration modal** with improved UX and progress indicators
- **Fixed 68 mismatched SOLR field configurations** that were incorrectly detected due to parameter swap
- **Reduced mismatches from 95 to 27** - significant improvement in field configuration accuracy …

fix: resolve SOLR field mismatch detection and fix functionality

---

lib/Db/ObjectEntity.php
lib/Service/GuzzleSolrService.php

This hotfix improves SOLR object reconstruction to provide more predictable and consistent results.
- Add hydrateObject method to ObjectEntity for better object hydration from SOLR data  
- Refactor reconstructObjectFromSolrDocument to use new hydration approach
- Improve consistency and predictability of SOLR search results
- Better object reconstruction from SOLR documents
- More predictable search results
- Improved data consistency

hotfix: improve SOLR object reconstruction for more predictable results

---

lib/Service/GuzzleSolrService.php
lib/Service/ObjectService.php
src/views/settings/sections/SolrConfiguration.vue

This PR optimizes SOLR performance and fixes UI display issues in the Field Configuration modal.
- Fixed table width issues by shortening column headers
- Ensures DocValues column is visible without horizontal scrolling
- Maintains all functionality while improving UX
- Split complex published condition into separate filters for better reliability
- Improves SOLR query performance and reliability
- Enhanced published parameter handling in ObjectService
- Ensures published filtering is properly passed through method parameters
- Maintains backward compatibility with existing API calls
- **Performance**: Better SOLR query performance with separate filters
- **UX**: DocValues column now visible in Field Configuration modal  
- **Reliability**: More robust published date filtering
- …

fix: optimize SOLR DocValues and published filtering

---

appinfo/routes.php
lib/Controller/SettingsController.php
lib/Service/GuzzleSolrService.php
lib/Service/SettingsService.php
lib/Setup/apply_solr_schema.php
src/store/settings.js
src/views/settings/sections/MultitenancyConfiguration.vue
src/views/settings/sections/RbacConfiguration.vue
src/views/settings/sections/SolrConfiguration.vue

Complete implementation of SOLR field management system with deletion and reindex capabilities to address field schema mismatches and enable proper index maintenance.
- ✅ **Backend**: deleteField method in GuzzleSolrService with SOLR Schema API
- ✅ **API Endpoint**: deleteSolrField endpoint with validation and error handling  
- ✅ **Frontend**: Delete buttons in both Mismatched and Extra Fields sections
- ✅ **UI/UX**: Loading spinners, confirmation dialogs, auto-refresh functionality
- ✅ **Backend**: reindexAll method with batch processing and progress tracking
- ✅ **API Endpoint**: reindexSolr endpoint with configurable parameters
- ✅ **Frontend**: Reindex button with confirmation and progress feedback
- ✅ **Performance**: Memory management, error collection, detailed statistics
- ✅ …

feat: comprehensive SOLR field management and reindex system

---

lib/Service/GuzzleSolrService.php

Lets store arrays in solr
